CREATE TABLE product (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  price INT NOT NULL,
  image_url VARCHAR(500) NOT NULL
);

CREATE TABLE option (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  quantity INT NOT NULL,
  product_id BIGINT NOT NULL,
  CONSTRAINT uk_product_option_name UNIQUE (product_id, name)
);

ALTER TABLE option
ADD CONSTRAINT fk_option_product_id
FOREIGN KEY (product_id)
REFERENCES product(id)
ON DELETE CASCADE;

CREATE TABLE member (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL
);

CREATE TABLE wish (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  member_id BIGINT NOT NULL,
  product_id BIGINT NOT NULL,
  amount INT NOT NULL
);

ALTER TABLE wish
ADD CONSTRAINT fk_wish_product_id
FOREIGN KEY (product_id)
REFERENCES product(id)
ON DELETE CASCADE;

ALTER TABLE wish
ADD CONSTRAINT fk_wish_member_id
FOREIGN KEY (member_id)
REFERENCES member(id)
ON DELETE CASCADE;
